name: mobile_steering_wheel_app
description: "Mobile steering wheel controller for truck simulators."
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Sensores
  sensors_plus: ^4.0.2

  # UDP
  udp: ^5.0.3

  # QR Scanner (conexión automática)
  mobile_scanner: ^5.2.3

  # Persistencia de ajustes
  shared_preferences: ^2.3.1

  # Mantener pantalla encendida
  wakelock_plus: ^1.1.4

  # Iconos
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0

  # Launcher icons
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptative_icon_foreground: "assets/icon/foreground.png"
  adaptative_icon_background: "assets/icon/background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
